name: Audit live site
on: push
jobs:
  audit:
    name: Audit the production site with Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://trnck.dev/
            https://trnck.dev/portfolio
            https://trnck.dev/stats
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
